### ISSUE TITLE
data有问题，迫使人发烧

### ISSUE THREAD

**Issue by Frankcsc** [Freedomisgood/Zju_health_checkin_helper#1]
今日是否有发热症状（高于37.2 ℃）？ Do you have a fever(above 37.2℃) today?
字段为'tw'（第一张图）
POST数据为'tw':'1'（第二张图）
可能相关的代码：（第三张图）
当事人情况：校外

（第一张图）
![image](https://user-images.githubusercontent.com/45666537/185035083-80c48386-5f68-4a36-bcde-2f36a5994997.png)

（第二张图）
![QQ图片20220817123606](https://user-images.githubusercontent.com/45666537/185035701-f1e8c90b-4710-4d99-8dca-35bbe000d240.jpg)

（第三张图）
![image](https://user-images.githubusercontent.com/45666537/185035443-4eb27ac1-eb18-4a0d-9021-9807d16de4ca.png)08-1f21038e-fb0b-4de0-a4c7-80369fa92c99.jpg)

**Comment by Freedomisgood** [comment]
> 今日是否有发热症状（高于37.2 ℃）？ Do you have a fever(above 37.2℃) today? 字段为'tw'（第一张图） POST数据为'tw':'1'（第二张图） 可能相关的代码：（第三张图） 当事人情况：校外
> 
> （第一张图） ![image](https://user-images.githubusercontent.com/45666537/185035083-80c48386-5f68-4a36-bcde-2f36a5994997.png)
> 
> （第二张图） ![QQ图片20220817123606](https://user-images.githubusercontent.com/45666537/185035701-f1e8c90b-4710-4d99-8dca-35bbe000d240.jpg)
> 
> （第三张图） ![image](https://user-images.githubusercontent.com/45666537/185035443-4eb27ac1-eb18-4a0d-9021-9807d16de4ca.png)08-1f21038e-fb0b-4de0-a4c7-80369fa92c99.jpg)

非常非常抱歉。自己在填写校外情况的时候勾错了....所以导致了错误抓包，后续也没有对参数进行校验，非常抱歉🥵

**Comment by Freedomisgood** [comment]
现已修复。

**Comment by Frankcsc** [comment]
请问在当天已经填报过的情况下，能不能通过修改前端，重新发起post请求抓包呢

**Comment by Freedomisgood** [comment]
应该不行，因为改了前端后发送请求其实也还是在发送POST请求，但是服务器在数据库里已经改状态，标识今天打卡了。如果再发生post，会显示{"msg":"今日已经打过卡了"}.




p.s. 这个是直接回复的邮件么， 我在github上没看到这条回复的记录。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Freedomisgood/Zju_health_checkin_helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月17日(星期三) 晚上8:24
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)





 
请问在当天已经填报过的情况下，能不能通过修改前端，重新发起post请求抓包呢

**Comment by Frankcsc** [comment]
是在github上回复的，不过后来我找到办法就把github上的删了。
具体方法就是在网页控制台输入
$vm.hasFlag=0
按钮就又可以重新点击了，不能影响浙大的数据，但是可以用于抓包



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月18日(周四) 上午9:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)




 应该不行，因为改了前端后发送请求其实也还是在发送POST请求，但是服务器在数据库里已经改状态，标识今天打卡了。如果再发生post，会显示{"msg":"今日已经打过卡了"}. 
 
 
 
 
 p.s. 这个是直接回复的邮件么， 我在github上没看到这条回复的记录。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Freedomisgood/Zju_health_checkin_helper"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年8月17日(星期三) 晚上8:24 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1) 
 
 
 
 
 
   
 请问在当天已经填报过的情况下，能不能通过修改前端，重新发起post请求抓包呢

**Comment by Freedomisgood** [comment]
哦哦好的。前端dom改起来都不难的，但后端数据已经没办法改变了，非常抱歉。按这样看，我自己已经提交了几天的发烧数据了....
那个定位的数据，不知你有没有无法定位的问题，我是改前端后直接填写才能提交抓包的。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Freedomisgood/Zju_health_checkin_helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 上午9:20
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)





 是在github上回复的，不过后来我找到办法就把github上的删了。 
 具体方法就是在网页控制台输入 
 $vm.hasFlag=0 
 按钮就又可以重新点击了，不能影响浙大的数据，但是可以用于抓包 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年8月18日(周四) 上午9:16 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1) 
 
 
 
 
  应该不行，因为改了前端后发送请求其实也还是在发送POST请求，但是服务器在数据库里已经改状态，标识今天打卡了。如果再发生post，会显示{"msg":"今日已经打过卡了"}.  
   
   
   
   
  p.s. 这个是直接回复的邮件么， 我在github上没看到这条回复的记录。  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "Freedomisgood/Zju_health_checkin_helper"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年8月17日(星期三) 晚上8:24  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)  
   
   
   
   
   
     
  请问在当天已经填报过的情况下，能不能通过修改前端，重新发起post请求抓包呢

**Comment by Frankcsc** [comment]
发烧的事没关系的😂我当时问就是想抓包。
定位的问题，我一直在电脑上抓包的，经验是，
1.开windows的定位服务，关梯子，正常定位
2.关windows的定位服务，开梯子，会定位到vpn的国内端服务器的位置
3.关windows的定位服务，关梯子，无法定位
关定位服务指的是把系统设置里的定位服务完全关闭，相当于电脑没有GPS

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月18日(周四) 上午9:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)




 哦哦好的。前端dom改起来都不难的，但后端数据已经没办法改变了，非常抱歉。按这样看，我自己已经提交了几天的发烧数据了.... 
 那个定位的数据，不知你有没有无法定位的问题，我是改前端后直接填写才能提交抓包的。 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Freedomisgood/Zju_health_checkin_helper"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年8月18日(星期四) 上午9:20 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1) 
 
 
 
 
 
  是在github上回复的，不过后来我找到办法就把github上的删了。  
  具体方法就是在网页控制台输入  
  $vm.hasFlag=0  
  按钮就又可以重新点击了，不能影响浙大的数据，但是可以用于抓包  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2022年8月18日(周四) 上午9:16  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)  
   
   
   
   
   应该不行，因为改了前端后发送请求其实也还是在发送POST请求，但是服务器在数据库里已经改状态，标识今天打卡了。如果再发生post，会显示{"msg":"今日已经打过卡了"}.   
     
     
     
     
   p.s. 这个是直接回复的邮件么， 我在github上没看到这条回复的记录。   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "Freedomisgood/Zju_health_checkin_helper"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2022年8月17日(星期三) 晚上8:24   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.***&amp;amp;amp;gt;;"State ***@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)   
     
     
     
     
     
       
   请问在当天已经填报过的情况下，能不能通过修改前端，重新发起post请求抓包呢

**Comment by Freedomisgood** [comment]
OKOK, win11的定位不太会用了，好像还是有点问题。我是去了input的click侦听事件+取消readonly来做的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Freedomisgood/Zju_health_checkin_helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 上午9:34
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)





 发烧的事没关系的😂我当时问就是想抓包。 
 定位的问题，我一直在电脑上抓包的，经验是， 
 1.开windows的定位服务，关梯子，正常定位 
 2.关windows的定位服务，开梯子，会定位到vpn的国内端服务器的位置 
 3.关windows的定位服务，关梯子，无法定位 
 关定位服务指的是把系统设置里的定位服务完全关闭，相当于电脑没有GPS 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年8月18日(周四) 上午9:24 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1) 
 
 
 
 
  哦哦好的。前端dom改起来都不难的，但后端数据已经没办法改变了，非常抱歉。按这样看，我自己已经提交了几天的发烧数据了....  
  那个定位的数据，不知你有没有无法定位的问题，我是改前端后直接填写才能提交抓包的。  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "Freedomisgood/Zju_health_checkin_helper"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年8月18日(星期四) 上午9:20  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)  
   
   
   
   
   
   是在github上回复的，不过后来我找到办法就把github上的删了。   
   具体方法就是在网页控制台输入   
   $vm.hasFlag=0   
   按钮就又可以重新点击了，不能影响浙大的数据，但是可以用于抓包   
     
     
     
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2022年8月18日(周四) 上午9:16   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.******@***.***&amp;amp;amp;gt;;   
   主题: Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)   
     
     
     
     
    应该不行，因为改了前端后发送请求其实也还是在发送POST请求，但是服务器在数据库里已经改状态，标识今天打卡了。如果再发生post，会显示{"msg":"今日已经打过卡了"}.    
       
       
       
       
    p.s. 这个是直接回复的邮件么， 我在github上没看到这条回复的记录。    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "Freedomisgood/Zju_health_checkin_helper"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2022年8月17日(星期三) 晚上8:24    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.***&amp;amp;amp;amp;gt;;"State ***@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [Freedomisgood/Zju_health_checkin_helper] data有问题，迫使人发烧 (Issue #1)    
       
       
       
       
       
         
    请问在当天已经填报过的情况下，能不能通过修改前端，重新发起post请求抓包呢
