### ISSUE TITLE
takein失败，response = self.sess.post返回的是404界面

### ISSUE THREAD

**Issue by Frankcsc** [Freedomisgood/Zju_health_checkin_helper#2]
今天突然不能打卡了，获取cookie和地理位置等都可以，就到了最后打卡提交数据一步，报错：
```
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
看了一下，是解码返回的提交数据时，json解码出错，遂看了一下返回页面，发现是404
```
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>404</title>
```
我的能力解决不了问题了，等大神解救。。。

**Comment by Freedomisgood** [comment]
> 今天突然不能打卡了，获取cookie和地理位置等都可以，就到了最后打卡提交数据一步，报错：
> 
> ```
> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> 看了一下，是解码返回的提交数据时，json解码出错，遂看了一下返回页面，发现是404
> 
> ```
> <!doctype html>
> <html lang="en">
> 
> <head>
>     <meta charset="UTF-8">
>     <title>404</title>
> ```
> 
> 我的能力解决不了问题了，等大神解救。。。

现在再试试呢？我本地和action上都能跑通

**Comment by Frankcsc** [comment]
> 现在再试试呢？我本地和action上都能跑通

莫名其妙可以了~
